name: Manual workflow

on:
  push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v3
      with:
        repository: my9oso6gqm/streamlit
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: 1
      run: git clone https://github.com/my9oso6gqm/streamlit.git
    - name: 2
      run: python streamlit/streamofconsciousness/add.py
    - name: 3
      run: |
          cd streamlit
          git config --global user.email 'rjhgshlc2x@gmail.com'
          git add *
          git push


