name: Manual workflow

on:
  push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v3
      with:
        repository: my9oso6gqm/streamlit
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: 1
      run: git clone https://github.com/my9oso6gqm/streamlit.git
    - name: 2
      run: python streamlit/streamofconsciousness/add.py
    - name: GIT commit and push all changed files
      env: 
       CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
       CI_COMMIT_AUTHOR: Continuous Integration
      run: |
       cd streamlit
       git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
       git config --global user.email "username@users.noreply.github.com"
       git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
       git push



